all:
  children:
    upstream:
      hosts:
        upstream-server:
          ansible_host: "" # Добавить IP адрес сервера Upstream
          ansible_user: root
          ansible_ssh_common_args: "-o IdentitiesOnly=yes -o PreferredAuthentications=password -o StrictHostKeyChecking=no"
    bridge:
      hosts:
        bridge-server:
          ansible_host: "" # Добавить ip адрес сервера Bridge
          ansible_user: root
          ansible_ssh_common_args: "-o IdentitiesOnly=yes -o PreferredAuthentications=password -o StrictHostKeyChecking=no"
