services:
  xray-bridge:
    image: teddysun/xray
    container_name: xray-bridge
    restart: always
    ports:
      - "13335:13335/tcp"
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    networks:
      - xray_net

  subscription:
    image: nginx:alpine
    container_name: xray-subscription
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./subscription:/usr/share/nginx/html:ro
      - ./nginx-sub.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - xray_net

networks:
  xray_net:
    driver: bridge
